services:
  - type: web
    name: xenocrm-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://crm-backend-y93k.onrender.com
      - key: REACT_APP_FRONTEND_URL
        value: https://crm-application-ictu.onrender.com
      - key: REACT_APP_COOKIE_DOMAIN
        value: .onrender.com
      - key: REACT_APP_GOOGLE_CLIENT_ID
        sync: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html